#!/bin/sh
. ./vars
HOSTNAME=`cat /etc/hostname`
for i in /etc/hosts $WWWROOT/index.html $WWWROOT/wiki/conf/local.php $WWWROOT/wiki/data/pages/start.txt
do
if [ -f $i ]
then
	echo sed -i.old "s/##HOSTNAME##/$HOSTNAME/g" $i
	sed -i.old "s/##HOSTNAME##/$HOSTNAME/g" $i
fi
done
