#!/bin/sh
### BEGIN INIT INFO
# Provides:          imx-libc-neon
# Required-Start:    mountdevsubfs
# Required-Stop:     
# Default-Start:     2 3 4 5 S
# Default-Stop:      0 1 6
# Short-Description: power button monitor daemon
# Description:       do a clean shutdown on power button press.
### END INIT INFO
case $1 in
start) /opt/outpostserver/bin/powerbutton ;;
esac
