#!/bin/sh
### BEGIN INIT INFO
# Provides:          rtcworkaround
# Required-Start:    mountdevsubfs
# X-Start-Before:    hostname keymap keyboard-setup procps pcmcia hwclock hwclockfirst hdparm hibernate-cleanup lvm2
# Required-Stop:     
# Default-Start:     2 3 4 5 S
# Default-Stop:      0 1 6
# Short-Description: cope with dead RTC battery
# Description:       try to cope as best we can with a dead RTC battery
### END INIT INFO
#This is a script to get around the dead RTC battery problem in tanzania
#it really sucks but its better than nothing, particularly when there is no
#network connection to set the time with.
year=`date +%Y`
lasttime=/var/local/lasttime
#Check first to see if we are in the 21st century, if so save the current time
#by touching a reference file.
save_time(){
	if [ $year -lt 2000 ]
	then
		exit 0;
	fi
	touch $lasttime
}

#First run ntpdate, if that fails then we check to see if the year is sane
#if that fails we restore the date to the timestamp of the lasttime file.
restore_time(){
	ntpdate tick.usno.navy.mil
	if [  $? -ne 0 ]
	then
		if [ $year -lt 2000 ]
		then
			date -s "`date -r $lasttime `"
		fi
	fi
exit 0
} 
	case $1 in
		start)
			restore_time
		;;
		stop)
			save_time
		;;
	esac


