.PHONY: sunsaver
all: sunsaver powerbutton
sunsaver:
	cd sunsaver && $(MAKE)

powerbutton:
	cd powerbutton && $(MAKE)

install:
	cd sunsaver && $(MAKE) install
	cd powerbutton && $(MAKE) install
clean:
	cd sunsaver && $(MAKE) clean
	cd powerbutton && $(MAKE) clean
