#!/bin/sh
#find all available remote sites by greping for ubiquity MAC
#addresses in the dnsmasq cache and copy thier /var/www (except for mirror) 
#to /var/www/mirror/sitename rsync the completed mirror back to the various
#remote sites when finished.
set -x 
if [ ! -d /var/www/mirror ]
then
	mkdir -p /var/www/mirror
fi
RSYNC_RSH="ssh -o StrictHostKeyChecking=no"
export RSYNC_RSH
cd /var/www/mirror
#Pull the remote sites into the central mirror directory.
	for i in `grep 01:00:27:22 /var/lib/misc/dnsmasq.leases | grep -v UBNT | awk '{ print $4}'`
	do
		echo pulling from "$i"
		if [ ! -d $i.tznet ]
		then
			mkdir $i.tznet
		fi
		
		#copy the wiki over
		rsync  --delete -a $i:/var/www/wiki $i.tznet 
                #make the mirrored wiki read-only
		cp /root/*.php $i.tznet/wiki/conf/
		rsync  --delete -a $i:/var/www/shared $i.tznet 
	done

#push the completed mirror to the remote sites after updating the mirror of local.tznet

if [ ! -d main.tznet ]
then
	mkdir main.tznet
fi
rsync  --delete -a /var/www/wiki main.tznet 
rsync  --delete -a /var/www/shared main.tznet 
cp /root/*.php main.tznet/wiki/conf


	for i in `grep 01:00:27:22 /var/lib/misc/dnsmasq.leases | grep -v UBNT | awk '{ print $4}'`
	do
		echo pushing to "$i"
		
		#push the mirror over
		rsync --delete --delete-excluded --exclude=mirror/$i.tznet -a /var/www/mirror $i.tznet:/var/www 
	done
